#!/bin/bash

#PBS -l select=1:ncpus=2:mem=8gb
#PBS -l walltime=11:59:00
#PBS -j oe
#PBS -o /srv/ccrc/data45/z3289452/GIT_REPOS/SymbolicDataAnalysis/code/Clustering_XunifYskew_1_1.out

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/srv/scratch/z3289452/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/srv/scratch/z3289452/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/srv/scratch/z3289452/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/srv/scratch/z3289452/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda activate OceanDataScience


cd /srv/ccrc/data45/z3289452/GIT_REPOS/SymbolicDataAnalysis/code


python Clustering.py XunifYskew 1 1
